app:
  id: "ai-orchestrator_api"
  port: "8080"
  env: "development"
  migrations_dir: "/app/db/migrations"

  backoff:
    min: "1s"
    max: "60s"
    factor: 2.0
    poll_interval: "50ms"
    max_retries: 5

postgres:
  host: postgres
  port: 5432
  user: postgres
  db_name: products_db

redis:
  uri: "redis:6379"

  pub_stream:
    id: "notifications"

    max_backlog: 1000
    use_del_approx: true
    read_count: 1
    block_time: "5s"
