app:
  id: "ai-orchestrator_worker"
  env: "development"

  backoff:
    min: "1s"
    max: "60s"
    factor: 2.0
    poll_interval: "50ms"
    max_retries: 5

redis:
  uri: "redis:6379"

  sub_stream:
    id: "notifications"

    max_backlog: 1000
    use_del_approx: true
    read_count: 1
    block_time: "5s"

    group:
      id: "notifications_group"